# 自動生成されるものはチェック対象から除外する
AllCops:
  Exclude:
    - "node_modules/**/*" # rubocop config/default.yml
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
    - "Gemfile.lock"
    - "bin/*"

# -- Style --
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AndOr:
  Enabled: false

# -- Layout --
Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 100

# -- Metrics --
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Metrics/AbcSize:
  Max: 24

Metrics/PerceivedComplexity:
  Max: 8
