default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['RAILS_DB_USER'] %>
  password:
  host: localhost
development:
  <<: *default
  database: focus_development
test:
  <<: *default
  database: focus_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: focus_production
